{{- define "packages" -}}
{{- range .packages -}}
{{- if ne .GroupName "" -}}
---
# Generated by hack/genref/generate.sh from the Go types in pkg/apis/ome/v1beta1
# of ome-projects/ome. Don't edit this file. Edit the doc comments on the types,
# or the templates in hack/genref, and run the script.
title: OME API
description: Look up the fields of every type in the ome.io/v1beta1 API, such as InferenceService, BaseModel and ClusterServingRuntime, in this generated reference.
generated: true
---

Every resource on this page has `apiVersion: {{ .DisplayName }}`. The page is generated from the Go types in [`pkg/apis/ome/v1beta1`](https://github.com/ome-projects/ome/tree/main/pkg/apis/ome/v1beta1), the same types the CRDs are generated from. Fields marked **Required** must be set when you create an object. OME writes `status`, so status fields aren't marked.
{{- $types := .VisibleTypes }}
{{- /*
	A status type is the type of a kind's status field, or a type that only
	status types use. OME writes these, so their fields aren't marked
	Required. $status has a character per visible type: "1" for a status
	type and "0" otherwise. Each pass adds the types that only the status
	types found so far use, until a pass adds none.
*/}}
{{- $status := "" }}
{{- range $t := $types }}
{{- $root := "0" }}
{{- range $types }}
{{- if or .IsExported (eq .Name.Name "RolloutPolicy") }}
{{- range .GetMembers }}{{ if and (eq .FieldName "status") (eq .GetType.Name.Name $t.Name.Name) }}{{ $root = "1" }}{{ end }}{{ end }}
{{- end }}
{{- end }}
{{- $status = print $status $root }}
{{- end }}
{{- range 20 }}
{{- $next := "" }}
{{- range $i, $t := $types }}
{{- $s := eq (index $status $i) 49 }}
{{- if and (not $s) $t.References }}
{{- $s = true }}
{{- range $ref := $t.References }}
{{- range $j, $u := $types }}{{ if and (eq $u.Name.Name $ref.Name.Name) (ne (index $status $j) 49) }}{{ $s = false }}{{ end }}{{ end }}
{{- end }}
{{- end }}
{{- if $s }}{{ $next = print $next "1" }}{{ else }}{{ $next = print $next "0" }}{{ end }}
{{- end }}
{{- if eq $next $status }}{{ break }}{{ end }}
{{- $status = $next }}
{{- end }}
{{- /*
	genref treats a type as a resource only when it has a +genclient marker.
	RolloutPolicy is a CRD kind without one, so it's placed among the kinds
	in alphabetical order by hand.
*/}}
{{- $rolloutPolicy := false }}
{{- range .VisibleTypes }}
{{- if and (not .IsExported) (eq .Name.Name "RolloutPolicy") }}{{ $rolloutPolicy = . }}{{ end }}
{{- end }}
{{- range .VisibleTypes }}
{{- if .IsExported }}
{{- if and $rolloutPolicy (lt $rolloutPolicy.Name.Name .Name.Name) }}
{{ template "kind" $rolloutPolicy }}
{{- $rolloutPolicy = false }}
{{- end }}
{{ template "kind" . }}
{{- end }}
{{- end }}
{{- if $rolloutPolicy }}
{{ template "kind" $rolloutPolicy }}
{{- end }}
{{- /*
	The removed fields come from comparing the types at v1.2.2 with main,
	so they're written by hand. New kinds and fields carry a +ome:since
	marker instead.
*/}}

## Removed in v1.3 {#removed-in-v1-3}

v1.3 removes these fields. Each item says what to use instead.

- `spec.kedaConfig` on an InferenceService, and `kedaConfig` on a component. Use `autoscaler` on each component, with `class: KEDA` and a `prometheus` trigger in `keda.triggers`.
- `scaleMetric` on a component. Use `autoscaler.hpa.metrics[0].resource.name`, with `class: HPA` in `autoscaler`.
- `scaleTarget` on a component. Use `autoscaler.hpa.metrics[0].resource.target.averageUtilization`.
- `spec.workers` on a ServingRuntime or ClusterServingRuntime. Use `spec.engineConfig.leader` and `spec.engineConfig.worker`, or the same fields on `spec.decoderConfig`.
- `status.components.<component>.latestCreatedRevision` on an InferenceService. Nothing replaces it. OMENative components report `latestReadyRevision` and `latestRolledoutRevision`.

A component is `engine`, `decoder` or `router` on an InferenceService, and `engineConfig`, `decoderConfig` or `routerConfig` on a ServingRuntime or ClusterServingRuntime.

## Supporting types

The resources above use these types in their fields.
{{- range $i, $t := $types }}
{{- if and (not .IsExported) (ne .Name.Name "RolloutPolicy") }}
{{ if eq (index $status $i) 49 }}{{ template "statustype" . }}{{ else }}{{ template "type" . }}{{ end }}
{{- end }}
{{- end }}
{{ end -}}
{{- end -}}
{{- end -}}
